# Generated by Django 4.0.1 on 2022-01-27 21:55

from django.db import migrations


def forwards_func(apps, schema_editor):
    Product = apps.get_model('backend', 'Product')

    Product.objects.bulk_create(
        [
            Product(
                name=f"Product {i}",
                image="https://bulma.io/images/placeholders/480x800.png",
                price=i * 10,
            )
            for i in range(6)
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
